#### IMPORT LIBRARY

In [1]:
import pandas as pd
import numpy as np

# visualization library
import seaborn as sns
import matplotlib.pyplot as plt

#### Read dataset

In [2]:
df = pd.read_csv('./Data/online_shoppers_intention.csv')

df.sample(10)

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
11880,0,0.000000,0,0.0,9,1352.000000,0.022222,0.044444,0.000000,0.0,Nov,4,1,7,2,Returning_Visitor,False,False
9478,0,0.000000,0,0.0,7,130.000000,0.057143,0.085714,0.000000,0.0,Nov,2,5,9,10,Returning_Visitor,True,False
748,1,10.500000,0,0.0,7,525.000000,0.000000,0.009524,0.000000,0.0,Mar,2,4,4,8,Returning_Visitor,False,False
7828,23,239.744534,3,624.6,409,9100.402959,0.004301,0.015935,6.277684,0.0,Jul,2,2,1,13,Returning_Visitor,True,False
6608,2,23.200000,0,0.0,11,119.200000,0.000000,0.015385,0.000000,0.0,Sep,2,2,2,2,New_Visitor,True,False
6001,1,21.200000,0,0.0,12,249.409524,0.015385,0.019231,0.000000,0.0,Oct,2,2,8,2,Returning_Visitor,True,False
10304,2,33.500000,0,0.0,108,2270.908333,0.005505,0.029664,0.000000,0.0,Nov,2,2,1,3,Returning_Visitor,False,False
11694,6,57.250000,0,0.0,36,1930.410714,0.012500,0.018083,21.395668,0.0,Nov,1,1,1,2,Returning_Visitor,False,True
3301,0,0.000000,0,0.0,57,980.833333,0.007143,0.044643,0.000000,0.8,May,2,2,3,11,Returning_Visitor,False,False
2637,14,230.106944,0,0.0,52,2059.109203,0.003747,0.008451,7.610431,0.0,May,2,2,1,13,Returning_Visitor,False,False

*************
### 1. EDA (Exploratory data analysis)
*************